EndV/Models/ErrorViewModel.cs
namespace EndV.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

EndV/Models/Form.cs
using Microsoft.Web.Mvc.Controls;
using sun.security.util;
using System.ComponentModel.DataAnnotations;

namespace EndV.Models
{
    public class Form
    {
        [Display(Name = "")]
        [Required(ErrorMessage = "Вам нужно ввести имя")]
        public string Name { get; set; }


        [Display(Name = "")]
        [Required(ErrorMessage = "Вам нужно ввести почту")]
        public string Email { get; set; }

    }
}

EndV/Models/Registration.cs
namespace EndV.Models
{
    public class Registration
    {
    }
}

EndV/Controllers/DjeimsController.cs
using Microsoft.AspNetCore.Mvc;

namespace EndV.Controllers
{
    public class DjeimsController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

EndV/Controllers/FeedbackController.cs
using Microsoft.AspNetCore.Mvc;

namespace EndV.Controllers
{
    public class FeedbackController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

EndV/Controllers/FormController.cs
using Microsoft.AspNetCore.Mvc;

namespace EndV.Controllers
{
    public class FormController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

EndV/Controllers/HomeController.cs
using EndV.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace EndV.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

   

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

EndV/Controllers/LuizaController.cs
using Microsoft.AspNetCore.Mvc;

namespace EndV.Controllers
{
    public class LuizaController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

EndV/Controllers/MinorCharactersController.cs
using Microsoft.AspNetCore.Mvc;

namespace EndV.Controllers
{
    public class MinorCharactersController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

EndV/Controllers/PrivacyController.cs
using Microsoft.AspNetCore.Mvc;

namespace EndV.Controllers
{
    public class PrivacyController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

EndV/Controllers/RegistrationController.cs
using Microsoft.AspNetCore.Mvc;

namespace EndV.Controllers
{
    public class RegistrationController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

EndV/Views/Djeims/Index.cshtml
@{
    ViewData["Title"] = "Djeims";
}

<html lang="ru">
<body id="body_djeims">
    <div class="container" id="container_djeims">
        <div class="image-container" id="image-container5">
            <img src="~/img/djeims.jpeg" alt="Description" class="image5">
        </div>
        <div class="text-container" id="text-container_djeims">
            <h2>Джеймс Норрингтон</h2>
            <p>
                Джеймс Норрингтон – молодой, харизматичный и язвительный журналист, чья страсть к профессии непоколебима. Он постоянно стремится к успеху и славе, используя свой острый ум и язвительный язык, чтобы прославиться в издательском мире. Его детство, омраченное тяжелыми испытаниями, обусловило его жажду власти и статуса,
                именно поэтому работа в издательстве,где помог ему попасть отец Луизы Райнхард, имеет для него огромное значение.
                Для Джеймса Норрингтона семья Райнхардов стала своеобразной опорой и центром его вселенной, сочетая важность близких людей с амбициями и желанием достичь еще большего в жизни. Его внутренний конфликт между верностью семье и стремлением к славе и власти делает его персонажем со множеством противоречий,
                искры которых летят насквозь при каждом его выступлении или решении. Джеймс представляется аудитории как запутанный узел эмоций и желаний, готовый развернуться в любую сторону, в зависимости от выбора между сердцем и разумом.
            </p>

        </div>
    </div>
</body>
</html>

EndV/Views/Feedback/Index.cshtml
@{
    ViewData["Title"] = "Feedback";
}

<html lang="ru" id="html_feedback">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Обратная связь</title>
</head>
<body id="body_feedback">

    <div class="container" id="container_feedback">
        <!-- Раздел формы слева -->
        <div class="form-section" id="form-section_feedback">
            <h2>Обратная связь</h2>
            <form id="feedbackForm">
                <div class="form-group">
                    <label for="name">Имя</label>
                    <input type="text" id="name" name="name" required>
                </div>
                <div class="form-group">
                    <label for="email">Электронная почта</label>
                    <input type="email" id="email" name="email" required>
                </div>
                <div class="form-group">
                    <label for="feedback">Отзыв</label>
                    <textarea id="feedback" name="feedback" required></textarea>
                </div>
                <button type="submit" class="submit-btn">Отправить</button>
            </form>
        </div>

        <!-- Раздел с контактной информацией справа -->
        <div class="info-section">
            <h2>Контактные данные</h2>
            <p>Процесс разработки игры — это увлекательное и трудоёмкое занятие, требующее много сил, ресурсов и времени. 
                Если вы хотите поддержать разработку и внести свой вклад в развитие нашего проекта, 
                мы будем очень благодарны за любую помощь! 
            </p>
            <div class="contact-widget">
                <span class="show-contact-info">Наши реквизиты</span>
                <div class="contact-list">
                    <p>Email: dymchenko_nady@mail.ru</p>
                    <p>Телефон: +79502876268</p>
                    <p>Реквизиты: 1234567890123456</p>
                </div>
            </div>
        </div>
    </div>
</body>
</html>

EndV/Views/Form/Index.cshtml
@model Form
@{
    ViewData["Title"] = "Form Page";
}

<html lang="ru">
<body id="body_form">
<div class="container" id="container_form">
    <div class="image-container">
        <img src="~/img/form.png" alt="Description" class="image4">
    </div>
    <div class="text-container">
        <h2>Предзаказ</h2>
            <p>
                Готовы стать частью мистической истории, где оживает древняя тайна и зло скрывается в самых глубинах человеческой души? Вступите в битву за искупление с Луизой – главной героиней нашей новой игры!
                Присоединяйтесь к бета-тестированию игры и помогите Луизе найти свой истинный путь к исцелению и спасению от зловещих сил. Узнайте, что такое настоящее испытание искупления в мире, где тьма и свет соперничают за власть над человеческими душами.
            </p>
    </div>
    <div class="form-container">
        <form method="post" asp-controller="Form" asp-action="Check">
            <label asp-for="Name"></label>
            <input asp-asp-for="Name" placeholder="Ваше имя" />
            <span asp-validation-for="Name"></span>

            <label asp-for="Email"></label>
            <input asp-asp-for="Email" placeholder="Ваша почта" />
            <span asp-validation-for="Email"></span>

            <input type="submit" value="Войти" class="submit-button" />
        </form>
            <button class="register-btn"> 
                <a href="Registration">Зарегистрироваться</a>
            </button>
    </div>
</div>
</body>
</html>

EndV/Views/GameMechanics/Index.cshtml
@{
    ViewData["Title"] = "Registration";
}

EndV/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<html lang="ru">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Главная страница</title>
    <link rel="stylesheet" href="styles.css">
</head>
<body>
    <div id="page1" class="page" style="background-image: url('/img/Home_slim_end.jpg');">
        <button class="my-button" onclick="redirectToPage()">Загрузить игру</button>
    </div>

    <div id="page2" class="page" style="background-image: url('/img/');">
        <div class="image-text-block">
            <img src="~/img/lor.jpeg" alt="Описание изображения" class="image">
            <div class="text">
                <h2>Лор</h2>
                <p>
                    Высокие небоскребы и старинные здания, скрытые в тени, призывают игроков на поиски разгадок и секретов, спрятанных в их стенах. Церкви и храмы выглядят как врата в параллельные миры, где возможны встречи с духами и силами, не поддающимися объяснению. Медиумы и ясновидящие тоже оказываются в центре внимания, предсказывая будущее и общаясь с потусторонними силами.
                    Некоторые медиумы принимают клиентов на дому, игнорируя возможные последствия своих контактов с загадочным миром. Их темные и безумные
                </p>
            </div>
        </div>
    </div>

    <div id="page3" class="page" style="background-image: url('/img/background_cards.jpg');">
        <div class="gallery">
            <a href="Djeims">
                <img src="~/img/djeims.jpeg" alt="Описание картинки 1" class="gallery-image">
            </a>
            <a href="Luiza">
                <img src="~/img/luiza.jpeg" alt="Описание картинки 2" class="gallery-image">
            </a>
        </div>
    </div>
    <div id="page4" class="page" style="background-image: url('/img/backgroundwidget.jpg'); background-size: 300px;" >
        <div class="carousel">
            <div class="card" data-card="1">
                <a href="MinorCharacters#page1">
                <img src="~/img/card3.jpeg" alt="Card 1">
                </a>
            </div>
            <div class="card" data-card="2">
                <a href="MinorCharacters#page2">
                <img src="~/img/card2.jpeg" alt="Card 2">
                </a>
            </div>
            <div class="card" data-card="3">
                <a href="MinorCharacters#page3">
                <img src="~/img/card1.jpeg" alt="Card 3">
                </a>
            </div>
            <div class="card" data-card="4">
                <a href="MinorCharacters#page4">
                <img src="~/img/card4.jpeg" alt="Card 4">
                </a>
            </div>
        </div>

        <script src="script.js"></script>
    </div>

    <script src="script.js"></script>
</body>
</html>

EndV/Views/Luiza/Index.cshtml
@{
    ViewData["Title"] = "Luiza";
}
<html lang="ru">
<body id="body_luiza">
    <div class="container" id="container_djeims">
        <div class="image-container" id="image-container5">
            <img src="~/img/luiza.jpeg" alt="Description" class="image5">
        </div>
        <div class="text-container" id="text-container_djeims">
            <h2>Луиза Райнхард </h2>
            <p>
                Луиза Райнхард – изысканная аристократка, чья хрупкая душа пронизана меланхолией и темными тайнами прошлого. Дочь главы одного из успешнейших издательских домов, она выросла в окружении роскоши и претенциозности,
                но скрывает в себе беспокойство и чувство вины за темные секреты своей семьи.
                Погружаясь в мир религии и духовности, Луиза ищет искупление за свои грехи и спасение от кошмаров, которые стали преследовать её после таинственного инцидента в арт-галерее.
                Погружаясь в мир религии и духовности, Луиза Райнхард ищет искупление за свои грехи и спасение от кошмаров, которые стали преследовать её после таинственного инцидента в арт-галерее.
                Сама по себе Луиза – загадочная и проникновенная личность, с глубокими глазами, в которых отражается невыразимая боль и стремление к истине.
                Её благородная осанка и изысканный облик скрывают бурные эмоции и внутренние раздоры, делая её персоной, чья сущность наполнена сложными пластами тайны и неизведанных граней души.

            </p>

        </div>
    </div>
</body>
<</html>

EndV/Views/MinorCharacters/Index.cshtml
@{
    ViewData["Title"] = "Minor Characters";
}

<html lang="ru">
<body>
    <div id="page1" class="page">
        <div class="image-text-block">
            <img src="~/img/card3.jpeg" alt="Описание изображения" class="image">
            <div class="text" id="text_minorchar">
                <h2>Тора</h2>
                <p>
                    Тора — это зловещий дух, окутанный тайной и мрачностью. Его силуэт постоянно меняется, как будто отражая тревоги и страхи тех, кто его видит. Он может принимать различные образы, от человека с искажёнными чертами до теней, которые хаотично движутся в темноте. Его глаза светятся холодным голубым светом, излучая жуткую ауру, которая заставляет людей чувствовать себя уязвимыми и напуганными.
                    В своей сущности Тора — это дух, который питается негативными эмоциями, особенно чувством вины и страха. Он становится олицетворением внутренних демонов Луизы, выступая как неумолимый противник, который ведет её по пути саморазрушения и страданий. Все его действия направлены на то, чтобы разжигать конфликт внутри неё, затягивая в игру, где она сталкивается с собственными потерями и сожалениями.
                </p>
            </div>
        </div>
    </div>

    <div id="page2" class="page">
        <div class="image-text-block">
            <div class="text" id="text_minorchar">
                <h2>Тенебриты</h2>
                <p>
                    Тенебриты — это маленькие черные человечки, обладающие уникальной способностью сливаться с тенями и создавать вокруг себя атмосферу беспокойства. Их тела словно вытянутые тени, лишенные четких очертаний, что делает их практически незаметными при слабом свете. светящиеся глаза, полные хитрости и злого удовольствия. При движении Тенебриты издают влажный звук, напоминающий капли воды, падающие на землю. Это создает жуткое впечатление, что они способны появляться и исчезать в любой момент, оставаясь лишь призраками ночи.
                    Хотя они служат Торре и олицетворяют легкомысленное зло, Тенебриты не являются агрессивными созданиями. Они могут неожиданно появляться перед Луизой, перемещая предметы или вызывая тихие звуки, чтобы отвлечь её внимание. Их игривое, но зловещее поведение создает ощущение постоянного присутствия угрозы, заставляя Луизу чувствовать себя на грани между реальностью и кошмаром. В этом взаимодействии они становятся символом внутреннего напряжения и страха, который Торра использует для манипуляции и контроля над своей жертвой.
                </p>
            </div>
            <img src="~/img/card2.jpeg" alt="Описание изображения" class="image">
        </div>
    </div>

    <div id="page3" class="page">
        <div class="image-text-block">
            <img src="~/img/card1.jpeg" alt="Описание изображения" class="image">
            <div class="text" id="text_minorchar">
                <h2>Октус</h2>
                <p>
                    Октус — зловещий дух с головой солнца, олицетворяющий двойственную природу света и тьмы. Его жуткая улыбка, фиксированная на лице, словно карикатура радости, вызывает у окружающих тревогу и беспокойство. При каждом его появлении раздается пронзительный звонкий смех, который проникает в душу, оставляя след из паранойи и страха. Подобно солнечному свету, он может быть притягательным, но за этой маской скрывается намерение причинить боль и разрушить.
                    Он находит удовольствие в проклятых шутках и психологических играх, ставя своих врагов перед трудными моральными выборами и заставляя их сталкиваться с собственными страхами. В то время как днем он становится сильнее, наполняя мир своим обманчивым светом, ночью его истинная природа проявляется в полной мере, когда таинственные теневые формы начинают преследовать тех, кто осмеливается противостоять ему. Октус — это не просто злой дух; он воплощение страха и искушения, которое заставляет людей помнить о своих слабостях и преодолевать их во имя спасения.
                </p>
            </div>
        </div>
    </div>
    <div id="page4" class="page">
        <div class="image-text-block">
            <div class="text" id="text_minorchar">
                <h2>Вивьен Кастро </h2>
                <p>
                    Вивьен Кастро — эксцентричная дама с яркими рыжими волосами, которые словно пламя сверкают на солнце и привлекают внимание окружающих. Вивьен известна своим остроумием и непредсказуемым поведением, что подчеркивает её харизму и индивидуальность. За внешней экстравагантностью скрывается проницательный ум и стремление к приключениям; она всегда готова идти на риск ради новых возможностей.
                    Получив заманчивое предложение от Луизы, Вивьен мгновенно погружается в этот заказ, понимая, что большие деньги могут открыть новые горизонты для её амбициозных проектов. Благодаря своим экстрасенсорным способностям, она не только ищет финансовую выгоду, но и интуитивно чувствует скрытые мотивы Луизы. Вивьен воспринимает эту ситуацию как шанс не только заработать, но и добавить немного ярких красок в свою жизнь, взаимодействуя с мистикой и загадками, окружающими её новую клиентку.
            </div>
            <img src="~/img/card4.jpeg" alt="Описание изображения" class="image">
        </div>
        <script src="script.js"></script>
    </div>

    <script src="script.js"></script>
</body>
</html>

EndV/Views/Privacy/Index.cshtml
@{
    ViewData["Title"] = "Privacy";
}


<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Политика конфиденциальности</title>
    <link rel="stylesheet" href="styles.css">
</head>


<body>
    <div class="container" id="container_privacy">
        <h1>Политика конфиденциальности</h1>
        <table>
            <thead>
                <tr>
                    <th>Закон о данных</th>
                    <th>Описание</th>
                </tr>
            </thead>
            <tbody>
                <tr>
                    <td>ФЗ-152 (Закон о персональных данных)</td>
                    <td>Регулирует обработку персональных данных и защищает права граждан на конфиденциальность.</td>
                </tr>
                <tr>
                    <td>ФЗ-149 (Закон об информации, информационных технологиях и о защите информации)</td>
                    <td>Определяет основы правового регулирования в сфере информации и защиты информации.</td>
                </tr>
                <tr>
                    <td>ФЗ-63 (Закон о электронной подписи)</td>
                    <td>Устанавливает правовой статус электронной подписи и порядок ее использования.</td>
                </tr>
                <tr>
                    <td>ФЗ-218 (Закон о государственной регистрации недвижимости)</td>
                    <td>Регулирует вопросы, связанные с защитой данных о недвижимости и собственниках.</td>
                </tr>
                <tr>
                    <td>ФЗ-230-ФЗ (Закон о защите прав потребителей)</td>
                    <td>Защищает права потребителей, включая право на информацию о товаре и услуги.</td>
                </tr>
            </tbody>
        </table>

        <h2>Права пользователей</h2>
        <ul>
            <li>Право на доступ к своим персональным данным</li>
            <li>Право на исправление неточных данных</li>
            <li>Право на удаление своих персональных данных</li>
            <li>Право на ограничение обработки своих данных</li>
            <li>Право на переносимость данных</li>
        </ul>
    </div>
</body>
</html>